### ISSUE TITLE
ember-cli compatibilty

### ISSUE THREAD

**Issue by ecbypi** [unspace/un-calendar#4]
Would it be possible to make `un-calendar` ember-cli compatible?  I'd be happy to work on a pull request.  

http://reefpoints.dockyard.com/2014/06/24/introducing_ember_cli_addons.html
http://hashrocket.com/blog/posts/building-ember-addons

**Comment by adambuczynski** [comment]
@ecbypi @ghedamat I'm trying to extend the calendar component in our Ember project in order to add some custom functionality, however, I'm having trouble importing the component into the app. How is the component namespaced?

The following throws an error saying the component can't be found:

```javascript
import UnCalendar from 'un-calendar/components/un-calendar';

export default UnCalendar.extend({

});
```

Other modules (e.g. ember-modal-dialog) are importable and extendable like this.

Thanks in advance.

**Comment by ghedamat** [comment]
@adambuczynski what you suggest seems correct, but this addon is outdated and uses an older version of ember-cli and the addon structure so I'd have to look into it to be sure.

also, it will definitely not work with recent ember (Glimmer +) due to some internals that we had to rely on at the time to be able to get decent performance.

I'll try to update the README shortly to make this clearer until we have time to  port this to a recent ember.

**Comment by adamreisnz** [comment]
Thanks. I'm trying to run it with Ember 1.12.1.

Yes, I noticed the folder structure seemed outdated, but since the add-on is otherwise functioning assumed it would be importable normally. I've resorted to just copying the entire code and tweaked it where needed for now.
